// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/threehook/aws-payload-offloading-go/s3 (interfaces: S3DaoClientI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockS3DaoClientI is a mock of S3DaoClientI interface.
type MockS3DaoClientI struct {
	ctrl     *gomock.Controller
	recorder *MockS3DaoClientIMockRecorder
}

// MockS3DaoClientIMockRecorder is the mock recorder for MockS3DaoClientI.
type MockS3DaoClientIMockRecorder struct {
	mock *MockS3DaoClientI
}

// NewMockS3DaoClientI creates a new mock instance.
func NewMockS3DaoClientI(ctrl *gomock.Controller) *MockS3DaoClientI {
	mock := &MockS3DaoClientI{ctrl: ctrl}
	mock.recorder = &MockS3DaoClientIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3DaoClientI) EXPECT() *MockS3DaoClientIMockRecorder {
	return m.recorder
}

// DeletePayloadFromS3 mocks base method.
func (m *MockS3DaoClientI) DeletePayloadFromS3(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePayloadFromS3", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePayloadFromS3 indicates an expected call of DeletePayloadFromS3.
func (mr *MockS3DaoClientIMockRecorder) DeletePayloadFromS3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePayloadFromS3", reflect.TypeOf((*MockS3DaoClientI)(nil).DeletePayloadFromS3), arg0, arg1)
}

// GetTextFromS3 mocks base method.
func (m *MockS3DaoClientI) GetTextFromS3(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextFromS3", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextFromS3 indicates an expected call of GetTextFromS3.
func (mr *MockS3DaoClientIMockRecorder) GetTextFromS3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextFromS3", reflect.TypeOf((*MockS3DaoClientI)(nil).GetTextFromS3), arg0, arg1)
}

// StoreTextInS3 mocks base method.
func (m *MockS3DaoClientI) StoreTextInS3(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTextInS3", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTextInS3 indicates an expected call of StoreTextInS3.
func (mr *MockS3DaoClientIMockRecorder) StoreTextInS3(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTextInS3", reflect.TypeOf((*MockS3DaoClientI)(nil).StoreTextInS3), arg0, arg1, arg2)
}
