// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/threehook/aws-payload-offloading-go/s3 (interfaces: S3DaoClntI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockS3DaoClntI is a mock of S3DaoClntI interface.
type MockS3DaoClntI struct {
	ctrl     *gomock.Controller
	recorder *MockS3DaoClntIMockRecorder
}

// MockS3DaoClntIMockRecorder is the mock recorder for MockS3DaoClntI.
type MockS3DaoClntIMockRecorder struct {
	mock *MockS3DaoClntI
}

// NewMockS3DaoClntI creates a new mock instance.
func NewMockS3DaoClntI(ctrl *gomock.Controller) *MockS3DaoClntI {
	mock := &MockS3DaoClntI{ctrl: ctrl}
	mock.recorder = &MockS3DaoClntIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3DaoClntI) EXPECT() *MockS3DaoClntIMockRecorder {
	return m.recorder
}

// DeletePayloadFromS3 mocks base method.
func (m *MockS3DaoClntI) DeletePayloadFromS3(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePayloadFromS3", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePayloadFromS3 indicates an expected call of DeletePayloadFromS3.
func (mr *MockS3DaoClntIMockRecorder) DeletePayloadFromS3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePayloadFromS3", reflect.TypeOf((*MockS3DaoClntI)(nil).DeletePayloadFromS3), arg0, arg1)
}

// GetTextFromS3 mocks base method.
func (m *MockS3DaoClntI) GetTextFromS3(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextFromS3", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextFromS3 indicates an expected call of GetTextFromS3.
func (mr *MockS3DaoClntIMockRecorder) GetTextFromS3(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextFromS3", reflect.TypeOf((*MockS3DaoClntI)(nil).GetTextFromS3), arg0, arg1)
}

// StoreTextInS3 mocks base method.
func (m *MockS3DaoClntI) StoreTextInS3(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreTextInS3", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreTextInS3 indicates an expected call of StoreTextInS3.
func (mr *MockS3DaoClntIMockRecorder) StoreTextInS3(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreTextInS3", reflect.TypeOf((*MockS3DaoClntI)(nil).StoreTextInS3), arg0, arg1, arg2)
}
